// AUTO-GENERATED FILE, then hand-completed.
// Generated by the Ballerina OpenAPI tool from specs/design/components/todo-api/openapi.yaml.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Delete a todo
    #
    # + return - returns can be any of following types
    # http:NoContent (Deleted)
    # http:NotFound (No todo with this id)
    resource function delete todos/[string todoId]() returns http:NoContent|ErrorNotFound {
        boolean removed = removeTodo(todoId);
        if removed {
            return http:NO_CONTENT;
        }
        return notFoundError(todoId);
    }

    # List all todos, oldest first
    #
    # + return - A page of todos
    resource function get todos(int 'limit = 20, int offset = 0) returns inline_response_200 {
        return listTodosPage('limit, offset);
    }

    # Get a single todo
    #
    # + return - returns can be any of following types
    # http:Ok (The todo)
    # http:NotFound (No todo with this id)
    resource function get todos/[string todoId]() returns Todo|ErrorNotFound {
        Todo? todo = findTodo(todoId);
        if todo is Todo {
            return todo;
        }
        return notFoundError(todoId);
    }

    # Create a new todo
    #
    # + return - returns can be any of following types
    # http:Created (The created todo)
    # http:BadRequest (The title is missing or empty)
    resource function post todos(@http:Payload NewTodo payload) returns http:Created|ErrorBadRequest {
        string? rawTitle = payload?.title;
        string title = rawTitle is string ? rawTitle.trim() : "";
        if title.length() == 0 {
            return badRequestError("title must not be blank");
        }
        Todo created = addTodo(title);
        return {body: created};
    }

    # Update a todo's title and/or completed status
    #
    # + return - returns can be any of following types
    # http:Ok (The updated todo)
    # http:BadRequest (The title is empty)
    # http:NotFound (No todo with this id)
    resource function put todos/[string todoId](@http:Payload UpdateTodo payload) returns Todo|ErrorBadRequest|ErrorNotFound {
        Todo? existing = findTodo(todoId);
        if existing is () {
            return notFoundError(todoId);
        }
        string? rawTitle = payload?.title;
        string? newTitle = ();
        if rawTitle is string {
            string trimmedTitle = rawTitle.trim();
            if trimmedTitle.length() == 0 {
                return badRequestError("title must not be blank");
            }
            newTitle = trimmedTitle;
        }
        boolean? newCompleted = payload?.completed;
        Todo? updated = updateTodoById(todoId, newTitle, newCompleted);
        if updated is Todo {
            return updated;
        }
        return notFoundError(todoId);
    }
}

public type Todo record {
    string id;
    string title;
    boolean completed;
    string createdAt;
};

public type UpdateTodo record {
    string title?;
    boolean completed?;
};

public type NewTodo record {
    string title?;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Todo[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};
